version: 2.1

image_config: &image_config

  IMAGE_NAME: circleci

  LINUX_VERSION: UBUNTU_FOCAL

  # RUBY_VERSION_NUM:

  # Default node version is the first value in the string below:
  NODE_VERSIONS_NUM: "20.12.1 24.14.1"

  # Default python version is the first value in the string below:
  PYTHON_VERSION_NUM: "3.6.8 3.7.2 3.8.5 3.12.10 3.14.3"

  GOVERS: "1.26.1"
  TFSEC_VERSION: "v1.28.5"
  TFLINT_VERSION: "v0.49.0"

jobs:
  build:
    machine:
      image: ubuntu-2204:current
    environment: *image_config

    steps:
      - checkout

      - run: bash scripts/generate.sh > Dockerfile

      - run: docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD

      - run: docker build -t $DOCKERHUB_USERNAME/$IMAGE_NAME:lambda_$CIRCLE_BRANCH .

      - run: docker push $DOCKERHUB_USERNAME/$IMAGE_NAME:lambda_$CIRCLE_BRANCH && sleep 10

      - store_artifacts:
          path: Dockerfile

workflows:
  dockerfile_wizard:
    jobs:
      - build:
          context: Global
