image_config: &image_config

  # make sure to set your Docker Hub username & password in CircleCI,
  # either as project-specific environment variables
  # or as resources in your organization's org-global Context

  IMAGE_NAME: circleci

  LINUX_VERSION: UBUNTU_FOCAL

  # RUBY_VERSION_NUM:

  # Default node version is the first value in the string below:
  NODE_VERSIONS_NUM: "18.18.0 20.12.1"

  # Default python version is the first value in the string below:
  PYTHON_VERSION_NUM: "3.6.8 3.7.2 3.8.5"

  GOVERS: "1.21.5"
  TFSEC_VERSION: "v1.28.5"
  TFLINT_VERSION: "v0.49.0"

  JAVA: true

  MYSQL_CLIENT: false

  POSTGRES_CLIENT: false

  DOCKERIZE: false

  BROWSERS: false

version: 2
jobs:
  build:
    machine: true
    environment:
      <<: *image_config

    steps:
      - checkout

      - run: bash scripts/generate.sh > Dockerfile

      - run: docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD

      - run: docker build -t $DOCKERHUB_USERNAME/$IMAGE_NAME:lambda_$CIRCLE_BRANCH .

      - run: docker push $DOCKERHUB_USERNAME/$IMAGE_NAME:lambda_$CIRCLE_BRANCH && sleep 10

      - store_artifacts:
          path: Dockerfile

workflows:
  version: 2
  dockerfile_wizard:
    jobs:
      - build:
          context: Global
